### ISSUE TITLE
FIX THE FOOTER

### ISSUE THREAD

**Issue by hiteacheryouare** [PorkyProductions/-de-Motivator#10]
# FIX the FOOTER

## INFO:
Make the footer look more presentable

## SKILLS NEEDED:
BASIC HTML, INTERMEDIATE CSS, AND (**OPTIONAL**) JAVASCRIPT 

## RULES:
- Follow our coding style, don't incorporate your own (not talking about design style here, I'm talking about syntax)
- Make the footer element look better

**Comment by jaas666** [comment]
PR submitted
